package(default_visibility = ["//java/com/bwe/readingoasis:__subpackages__"])

java_library(
    name = "repository",
    srcs = glob(["*.java"]),
    deps = [
        "//java/com/bwe/readingoasis/entity",
        "//third_party/java/spring_boot:context",
        "//third_party/java/spring_boot:jpa",
    ],
)
