java_library(
    name = "controller",
    srcs = glob(["*.java"]),
    visibility = ["//java/com/bwe/hello:__subpackages__"],
    deps = [
        "//java/com/bwe/hello/model",
        "//java/com/bwe/hello/service",
        "//third_party/java/spring_boot",
    ],
)
