java_library(
    name = "entity",
    srcs = glob(["*.java"]),
    visibility = ["//java/com/bwe/readingoasis:__subpackages__"],
    deps = [
        "//java/com/bwe/readingoasis/model",
        "//third_party/java/hibernate",
        "//third_party/java/spring_boot:context",
        "//third_party/java/spring_boot:jpa",
    ],
)
