package(default_visibility = ["//java/com/bwe/readingoasis:__pkg__"])

java_library(
    name = "controller",
    srcs = glob(["*.java"]),
    deps = [
        "//java/com/bwe/readingoasis/entity",
        "//java/com/bwe/readingoasis/model",
        "//java/com/bwe/readingoasis/service",
        "//third_party/java/spring_boot:beans",
        "//third_party/java/spring_boot:context",
        "//third_party/java/spring_boot:data_jpa",
        "//third_party/java/spring_boot:web",
    ],
)
