package(default_visibility = ["//java/com/bwe/readingoasis:__subpackages__"])

java_library(
    name = "model",
    srcs = glob(["*.java"]),
    deps = [
        "//third_party/java/auto_value",
        "//third_party/java/spring_boot:web",
    ],
)
