package(default_visibility = ["//java/com/bwe/readingoasis:__subpackages__"])

java_library(
    name = "constant",
    srcs = [
        "ReadingOasisConstants.java",
    ],
    deps = ["//third_party/java/spring_boot:jpa"],
)
