java_library(
    name = "service",
    srcs = glob(["*.java"]),
    visibility = ["//java/com/bwe/hello:__subpackages__"],
    deps = [
        "//java/com/bwe/hello/model",
        "//third_party/java/spring_boot:context",
    ],
)
