package(default_visibility = [
    "//java:__subpackages__",
    "//javatests:__subpackages__",
])

java_library(
    name = "dialect",
    srcs = ["SQLiteDialect.java"],
    deps = [
        "//java/com/bwe/sqlite/identity",
        "//third_party/java/hibernate",
        "//third_party/java/persistence",
    ],
)
