package(default_visibility = ["//java/com/bwe/readingoasis:__subpackages__"])

java_library(
    name = "handler",
    srcs = glob(["*.java"]),
    deps = [
        "//java/com/bwe/readingoasis/exception",
        "//java/com/bwe/readingoasis/model",
        "//third_party/java/spring_boot:core",
        "//third_party/java/spring_boot:web",
        "//third_party/java/spring_boot:webmvc",
    ],
)
